% Example MATLAB script for sending telemetry from Simulink/MATLAB to the
% SCADA dashboard over UDP.

scadaHost = "127.0.0.1";
scadaPort = 5005;   % Must match the dashboard "Local UDP port"

u = udpport("datagram", "IPV4");

payload = struct( ...
    "P_PV", 42.5, ...
    "P_EOLIEN", 18.2, ...
    "P_CHARGE", 55.0, ...
    "P_BATTERIE", -6.5, ...
    "SOC", 72.0, ...
    "P_RESEAU", 0.8, ...
    "TENSION_RESEAU", 398.7, ...
    "FREQUENCE_RESEAU", 49.98, ...
    "IRRADIANCE", 845.0, ...
    "VITESSE_VENT", 7.4);

write(u, jsonencode(payload), "string", scadaHost, scadaPort);
